### PR TITLE
fix: now it lists all of the certificates in the aws account

### LINKED ISSUE #40: When looking for existing certificates, plugin lists only first 100 certs
As in the description.

```
 getExistingCertificate() {
    return this.listCertificates().then(data => {

      let existingCerts = data.CertificateSummaryList.filter(cert => cert.DomainName === this.domain);
      if (existingCerts.length > 0) {
        return existingCerts[0];
      }
      return undefined;
    });
  }
```

This piece of code should be checking if the nextToken is defined and keep on listing certificates.

### PR DESCRIPTION
**Pull request by PatrykMilewski**
Fixes #40

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -523,8 +530,8 @@ class CreateCertificatePlugin {
     }
 
     return this.listCertificates()
-      .then(({ CertificateSummaryList }) => {
-        let cert = CertificateSummaryList.filter(({ DomainName }) => DomainName == domainName)[0];
+      .then((certificates) => {
```
Comment (G-Rath) [inline index.js:533]:
```suggestion
      .then(certificates => {
```

nit: we can drop these

File: index.js [hunk 2]
```diff
@@ -130,8 +130,15 @@ class CreateCertificatePlugin {
       .then(() => this.serverless.cli.log('serverless-certificate-creator: disabled.'));
   }
 
-  listCertificates() {
-    return this.acm.listCertificates({}).promise();
+  listCertificates(NextToken) {
```
Comment (G-Rath) [inline index.js:133]: nit: would be good to use `async/await` instead of `.then`, to ensure a Promise is always returned and improve readability.

**Review by G-Rath — COMMENTED** [review]
Looks good - got a couple of comments that would be nice to have actioned if you don't mind :)

File: index.js (hunk 2 above)
Comment (PatrykMilewski) [reply index.js:133]: I'm not sure about this one, because I would expect, that all of the Serverless plugins code should match ES5, because there is no transpilation done. Are you sure, that we are good to use async/await? I thought that's one of the reasons, why this plugin uses `.then`

Comment (G-Rath) [reply index.js:133]: Good point - I thought we were already using `async/await` somewhere else but I realised I was thinking of `serverless` itself 😅

**Comment by danielwaghorn** [comment]
+1 this PR fixes an issue for us relating to an account with a large number of provisioned certs.
