### PR TITLE
fix(index): disable plugin for Chinese region

### LINKED ISSUE #7: Disable the plugin for Chinese region
China doesn't have ACM, so when deploying to the Chinese region, the certificate summary causes our otherwise successful deployment to crash.

### PR DESCRIPTION
**Pull request by muja**
fixes #7

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -116,7 +116,11 @@ class CreateCertificatePlugin {
    * Creates a certificate for the given options set in serverless.yml under custom->customCertificate
    */
   createCertificate() {
-
+    const region = this.options.region ? this.options.region : this.serverless.service.provider.region;
+    if (region.startsWith('cn-')) {
+      this.serverless.cli.log('Skipping certificate summary in Chinese region');
```
Comment (schwamster) [inline index.js]: this log msg does not fit what the code is doing

File: index.js [hunk 2]
```diff
@@ -116,7 +116,11 @@ class CreateCertificatePlugin {
...
+      return true;
+    }
     this.initializeVariables();
     if (!this.enabled) {
       return this.reportDisabled();
```
Comment (schwamster) [inline index.js]: what about changing the enabled flag instead of  just returning true?

File: index.js [hunk 3]
```diff
@@ -246,6 +250,11 @@ class CreateCertificatePlugin {
    * Prints out a summary of all domain manager related info
    */
   certificateSummary() {
+    const region = this.options.region ? this.options.region : this.serverless.service.provider.region;
+    if (region.startsWith('cn-')) {
```
Comment (schwamster) [inline index.js]: 2nd use of cn- -> what about a constant or list of "unsupported regions"

File: index.js (hunk 1 above)
Comment (muja) [reply index.js]: Can you elaborate?

File: index.js (hunk 2 above)
Comment (muja) [reply index.js]: What does the return value mean here?

We have certificate creator / summary enabled as we want them in supported regions... But it throws an error in China.

File: index.js (hunk 3 above)
Comment (muja) [reply index.js]: Yes that is also an option.

Comment (muja) [reply index.js]: I remembered why I decided to not go with "unsupported regions": Yes we can have a list of regions but what if AWS decides to add a new region? We'd have to maintain this list. We can assume that AWS will ship every new region with Certificate Manager as they have in the past. This is just a China specific issue as the Chinese government does not allow straight forward ways of issuing a certificate. This code can be expected to be future-proof as you don't have to consider new Chinese regions (they will be excluded automatically) and new other regions (they will be supported automatically).

File: index.js (hunk 1 above)
Comment (schwamster) [reply index.js]: the log you added here says - skipping certificate summary. But it is actually skipping the creation of the certificate all together

Comment (muja) [reply index.js]: You're right. Thanks! :)

File: index.js (hunk 3 above)
Comment (schwamster) [reply index.js]: well, it is hard to predict the future :) But if aws decides to add a new region and it supports acm as in the past the code still works. If Aws decides to add a new region that does not support acm we have to add it anyways. I am not saying you should abandon the region wildcard approach => cn- 
I would just much rather have a list that has a name e.g. unsupportedRegions than a magical string we use two times

File: index.js (hunk 2 above)
Comment (schwamster) [reply index.js]: what i tried to say here is -> there is already code that logs, that the plugin is disabled if the flag "enabled" is false and exits the plugin. so instead of just returning in the if i might just set the enabled flag to false and continue

Comment (muja) [reply index.js]: OK I'll update everything.

**Comment by muja** [comment]
I hope this resolves the issues.

**Comment by schwamster** [comment]
thx @muja made some minor changes and published the package with version 1.0.7
